export type Prompt = {
  id: number;
  sourceId: string;
  title: string;
  category: string;
  description: string;
  prompt: string;
  tags: string[];
  status: string;
  readiness: string;
  requiredInputs: string;
  outputFormat: string;
  complexity: string;
  frequency: string;
  value: string;
};

export const prompts: Prompt[] = [
  {
    "id": 1,
    "sourceId": "PL-GRO-01",
    "title": "UAE Government Relations Daily Briefing",
    "category": "Government Relations",
    "description": "Generate a current, employer-focused regulatory briefing for UAE operations.",
    "prompt": "Prepare a concise UAE Government Relations Daily Briefing for [RECIPIENT / TEAM].\n\nResearch only reliable updates published or materially updated within the last [LOOKBACK PERIOD]. Prioritize official UAE government, authority, regulator, municipality, ministry, free-zone, labour, immigration, visa, licensing, pension, insurance, payroll, and employer-service sources. Use reputable English-language reporting only where an official source is unavailable.\n\nInclude only updates with a clear practical impact on employers, employees, visas, residency, work permits, Emiratisation, licensing, labour compliance, payroll, pensions, insurance, municipalities, or free zones.\n\nFor each qualifying update, provide: Authority | Headline | 3–4 line employer-impact brief | Source link labelled “Click here” | Required action or watchpoint.\n\nDo not add placeholder rows, unchanged-service notices, routine-monitoring notes, or stale/unverified items. If no qualifying update is found, return exactly: No qualifying verified updates found for [DATE RANGE].\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "gro",
      "uae",
      "government",
      "relations",
      "daily",
      "briefing",
      "generate",
      "current",
      "employer",
      "focused"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready after inputs",
    "requiredInputs": "RECIPIENT / TEAM; LOOKBACK PERIOD; DATE RANGE",
    "outputFormat": "One concise table, 1–5 rows; no summary",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 2,
    "sourceId": "PL-HRA-01",
    "title": "Pre-Hire Process Performance Analysis",
    "category": "HR Operations Analytics",
    "description": "Identify delays, bottlenecks, and affected groups across the pre-hire process using Microsoft 365 records.",
    "prompt": "Review the [NEW HIRE TRACKER], [NEW HIRE HISTORY LOG], and [TEAMS CHANNEL / STATUS CHANGE HISTORY] for the period [DATE RANGE].\n\nUse the status-change history as the source of truth for process dates, hand-offs, and elapsed time. Use the main tracker only for employee attributes such as nationality, employment type, location, business unit, application type, and recruiter.\n\nAnalyse:\n1. End-to-end processing time and time spent at each stage.\n2. The longest delays, recurring bottlenecks, rework, and approval waits.\n3. Differences by nationality, employment type, location, application type, or other available attributes.\n4. Cases outside the agreed service level of [SLA / TARGET DAYS].\n5. Evidence-based operational actions to reduce time.\n\nReturn: Executive summary | KPI table | Stage-duration analysis | Segment comparison | Outlier cases | Root causes | Prioritised recommendations. Do not infer missing dates or causation. State data limitations clearly.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "hra",
      "pre",
      "hire",
      "process",
      "performance",
      "analysis",
      "operations",
      "analytics",
      "identify",
      "delays"
    ],
    "status": "Approved Core",
    "readiness": "94% | Ready with source files",
    "requiredInputs": "NEW HIRE TRACKER; NEW HIRE HISTORY LOG; TEAMS CHANNEL / STATUS CHANGE HISTORY; DATE RANGE; SLA / TARGET DAYS",
    "outputFormat": "Executive report with KPI tables and prioritised actions",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 3,
    "sourceId": "PL-PPA-01",
    "title": "New-Hire Intake Data Architecture for Power Apps",
    "category": "Power Apps / SharePoint",
    "description": "Convert a process with branching logic into a structured, build-ready data model.",
    "prompt": "Design a build-ready data structure for a [PROCESS NAME] intake solution in SharePoint and Power Apps.\n\nProcess context: [PASTE PROCESS / REQUIREMENTS].\nApplication types: [LIST TYPES].\nFor each application type, required documents, questions, approvals, service targets, and exceptions may differ.\n\nCreate:\n1. A master SharePoint list with the core case fields.\n2. A requirements matrix that maps each application type to conditional fields, documents, approvals, and routing.\n3. Lookup/reference lists needed for controlled values.\n4. The Power Apps branching logic in clear IF/THEN rules.\n5. A case status model, ownership model, and audit fields.\n6. A recommended minimum viable build sequence.\n\nUse simple field names, specify field types, indicate mandatory fields, and avoid duplicate data. Do not write code unless explicitly requested.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "ppa",
      "new",
      "hire",
      "intake",
      "data",
      "architecture",
      "power",
      "apps",
      "sharepoint",
      "convert"
    ],
    "status": "Approved Core",
    "readiness": "92% | Ready with process details",
    "requiredInputs": "PROCESS NAME; PASTE PROCESS / REQUIREMENTS; LIST TYPES",
    "outputFormat": "Solution blueprint with tables and logic rules",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 4,
    "sourceId": "PL-SPO-01",
    "title": "UAE Offboarding Workspace Build Brief",
    "category": "SharePoint / HR Operations",
    "description": "Define a clear SharePoint workspace for visa cancellation, final settlement, and operational offboarding.",
    "prompt": "Create a detailed build brief for a SharePoint page called “[WORKSPACE NAME]” supporting [COUNTRY / BUSINESS UNIT] offboarding.\n\nUsers: [USER GROUPS].\nProcess scope: [VISA CANCELLATION, WORK PERMIT, DEPENDANTS, FINAL SETTLEMENT, ASSET RETURN, OTHER].\nAvailable systems and trackers: [LIST].\n\nDesign:\n- Page hierarchy and navigation\n- Key actions and prominent buttons\n- Tracker views and filters\n- Case submission form requirements\n- Process steps, owner responsibilities, and service targets\n- Document library structure and naming rules\n- Alerts, FAQs, and escalation guidance\n- Access principles and sensitive-data safeguards\n\nUse a clean operational design with practical, buildable labels. Keep the experience simple for end users and manageable for the GRO team.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "spo",
      "uae",
      "offboarding",
      "workspace",
      "build",
      "brief",
      "sharepoint",
      "operations",
      "define",
      "clear"
    ],
    "status": "Approved Core",
    "readiness": "92% | Ready with process details",
    "requiredInputs": "WORKSPACE NAME; COUNTRY / BUSINESS UNIT; USER GROUPS; VISA CANCELLATION, WORK PERMIT, DEPENDANTS, FINAL SETTLEMENT, ASSET RETURN, OTHER; LIST",
    "outputFormat": "Page blueprint, content hierarchy, lists, and build checklist",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 5,
    "sourceId": "PL-COM-01",
    "title": "Operational Email Refinement",
    "category": "Business Communication",
    "description": "Rewrite internal or external operational emails to be concise, clear, and action-oriented.",
    "prompt": "Rewrite the message below for [AUDIENCE].\n\nObjective: [OBJECTIVE].\nTone: [PROFESSIONAL / FRIENDLY / FIRM / ESCALATION].\nRequired action: [ACTION].\nDeadline or timing: [DATE / TIME].\nNon-negotiable facts to preserve: [FACTS].\n\nKeep it concise, natural, and direct. Improve grammar, structure, and clarity without changing the intended meaning. Remove repetition and vague wording. Flag only material legal, HR, or reputational risk.\n\nReturn only the final ready-to-send message.\n\nOriginal message:\n[PASTE TEXT]\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "com",
      "operational",
      "email",
      "refinement",
      "business",
      "communication",
      "rewrite",
      "internal",
      "external",
      "emails"
    ],
    "status": "Approved Core",
    "readiness": "98% | Ready to use",
    "requiredInputs": "AUDIENCE; OBJECTIVE; PROFESSIONAL / FRIENDLY / FIRM / ESCALATION; ACTION; DATE / TIME; FACTS; PASTE TEXT",
    "outputFormat": "Final ready-to-send email or Teams message only",
    "complexity": "Basic",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 6,
    "sourceId": "PL-ATM-01",
    "title": "Teams Notification Content and Layout",
    "category": "Power Automate / Teams",
    "description": "Create reliable, readable Teams notification content for a Power Automate flow.",
    "prompt": "Create the content for a Microsoft Teams notification generated by Power Automate.\n\nNotification purpose: [PURPOSE].\nTrigger: [TRIGGER].\nAudience: [RECIPIENTS].\nFields available from the flow: [FIELD LIST].\nPrimary action link: [URL FIELD].\nBrand requirements: [COLOURS / STYLE].\nConstraints: [PLAIN TEXT / HTML SUPPORTED / NO ADAPTIVE CARD / OTHER].\n\nProvide:\n1. A short clear headline.\n2. A compact body using no more than [NUMBER] lines or sections.\n3. Labels for each dynamic field.\n4. A clear call to action.\n5. The exact text or supported HTML only, based on the constraints.\n\nAvoid raw markup that the selected Teams action will display as text. Keep it scannable on desktop and mobile.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "atm",
      "teams",
      "notification",
      "content",
      "layout",
      "power",
      "automate",
      "create",
      "reliable",
      "readable"
    ],
    "status": "Approved Core",
    "readiness": "94% | Ready with platform details",
    "requiredInputs": "PURPOSE; TRIGGER; RECIPIENTS; FIELD LIST; URL FIELD; COLOURS / STYLE; PLAIN TEXT / HTML SUPPORTED / NO ADAPTIVE CARD / OTHER; NUMBER",
    "outputFormat": "Copy-ready Teams content or supported HTML",
    "complexity": "Intermediate",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 7,
    "sourceId": "PL-AQA-01",
    "title": "Power Automate Output Debugging",
    "category": "Automation Quality",
    "description": "Diagnose why a flow or prompt produces the wrong format, extra text, raw HTML, or unreliable data.",
    "prompt": "Diagnose and fix this automation output problem.\n\nPlatform and action: [PLATFORM / ACTION NAME].\nIntended result: [EXPECTED OUTPUT].\nActual result: [PASTE ACTUAL OUTPUT OR ERROR].\nCurrent prompt / expression / configuration: [PASTE].\nConstraints: [DELIVERY FORMAT, CHARACTER LIMIT, CONNECTORS, APPROVALS, ETC.].\n\nIdentify:\n1. The most likely root cause.\n2. The exact minimum change needed.\n3. A corrected prompt, expression, or configuration block.\n4. A short test case and expected result.\n5. Any platform limitation that makes the requested output unreliable.\n\nDo not redesign the full solution unless the current approach cannot meet the requirement.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "aqa",
      "power",
      "automate",
      "output",
      "debugging",
      "automation",
      "quality",
      "diagnose",
      "why",
      "flow"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready to use",
    "requiredInputs": "PLATFORM / ACTION NAME; EXPECTED OUTPUT; PASTE ACTUAL OUTPUT OR ERROR; PASTE; DELIVERY FORMAT, CHARACTER LIMIT, CONNECTORS, APPROVALS, ETC.",
    "outputFormat": "Root cause, minimal fix, corrected configuration, test case",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 8,
    "sourceId": "PL-PRQ-01",
    "title": "UAE Government Update Qualification Filter",
    "category": "Prompt Reliability",
    "description": "Ensure a research or scheduled briefing includes only relevant, verified regulatory developments.",
    "prompt": "Before drafting the briefing, screen each candidate update against these criteria.\n\nInclude an update only when it is:\n- Published or materially updated within [LOOKBACK PERIOD].\n- Verified through an official source, or a reputable English-language source when no official source is available.\n- Distinct from other selected updates.\n- Relevant to [EMPLOYER / EMPLOYEE MOBILITY / VISA / LICENSING / LABOUR / PAYROLL / PENSION / INSURANCE / MUNICIPALITY / FREE-ZONE OPERATIONS].\n- Specific enough to explain a practical impact or watchpoint.\n\nExclude:\n- Unchanged services, generic announcements, opinion content, duplicate reporting, unsupported claims, and updates without a clear operational implication.\n\nReturn only qualifying updates. Do not create filler rows to reach a target count. For every included item, state the source, publication or material-update date, impact, and recommended watchpoint.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "prq",
      "uae",
      "government",
      "update",
      "qualification",
      "filter",
      "reliability",
      "ensure",
      "research",
      "scheduled"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready after inputs",
    "requiredInputs": "LOOKBACK PERIOD; EMPLOYER / EMPLOYEE MOBILITY / VISA / LICENSING / LABOUR / PAYROLL / PENSION / INSURANCE / MUNICIPALITY / FREE-ZONE OPERATIONS",
    "outputFormat": "Qualified update list or a single no-update statement",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 9,
    "sourceId": "PL-DES-01",
    "title": "Executive Document Visual Enhancement",
    "category": "Document Design",
    "description": "Transform a text-heavy report into a visual, executive-level document without changing content.",
    "prompt": "Enhance the attached [DOCUMENT TYPE] into a visually strong executive-level document.\n\nPreserve all existing wording, facts, data, and meaning. Do not add, remove, or alter content.\n\nImprove layout, hierarchy, and storytelling through:\n- Executive summary dashboard\n- KPI cards, scorecards, and progress indicators\n- Timelines, process flows, milestone trackers, and comparison matrices\n- Charts and diagrams created only from existing data\n- Clear section dividers, callout boxes, and visual emphasis\n- Professional spacing, alignment, typography, and page consistency\n\nBrand direction: [BRAND GUIDELINES / COLOURS].\nAudience: [AUDIENCE].\nOutput format: [WORD / POWERPOINT / PDF].\n\nWhere data is insufficient for a visual, use a structured text layout instead of inventing values.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "des",
      "executive",
      "document",
      "visual",
      "enhancement",
      "design",
      "transform",
      "text",
      "heavy",
      "report"
    ],
    "status": "Approved Core",
    "readiness": "92% | Ready with source files",
    "requiredInputs": "DOCUMENT TYPE; BRAND GUIDELINES / COLOURS; AUDIENCE; WORD / POWERPOINT / PDF",
    "outputFormat": "Visually enhanced document preserving all content",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 10,
    "sourceId": "PL-DES-02",
    "title": "Style and Design System Extraction",
    "category": "Document Design",
    "description": "Extract a reusable visual system from a reference document for use on another document.",
    "prompt": "Analyse the attached reference document and create a complete Style & Design System that another designer can apply to a different document without changing its content.\n\nDocument type: [TYPE].\nBrand constraints: [BRAND / COLOUR / FONT REQUIREMENTS].\n\nDefine:\n- Page grid, margins, spacing rhythm, and section structure\n- Typography hierarchy with sizes, weights, alignment, and use cases\n- Colour palette and role of each colour\n- Header, footer, title, subtitle, and page-number treatments\n- Table, chart, callout, icon, process-flow, and image styles\n- Rules for long text, key messages, lists, and data-heavy pages\n- Do and do not rules for consistency\n\nReturn a practical specification, not a critique. Make every instruction specific enough to apply directly.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "des",
      "style",
      "design",
      "system",
      "extraction",
      "document",
      "extract",
      "reusable",
      "visual",
      "reference"
    ],
    "status": "Approved Core",
    "readiness": "92% | Ready with source files",
    "requiredInputs": "TYPE; BRAND / COLOUR / FONT REQUIREMENTS",
    "outputFormat": "Reusable style guide with precise application rules",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 11,
    "sourceId": "PL-DES-03",
    "title": "Apply a Reference Design System",
    "category": "Document Design",
    "description": "Apply an established visual system to a new document while preserving content.",
    "prompt": "Apply the complete Style & Design System from [REFERENCE DOCUMENT / STYLE GUIDE] to the attached [TARGET DOCUMENT].\n\nPreserve the target document’s content, wording, facts, and order exactly. Do not rewrite, summarise, add, or remove content.\n\nApply the reference system consistently to:\n- Page layout, margins, spacing, typography, and hierarchy\n- Headers, footers, titles, section dividers, and page numbers\n- Tables, charts, diagrams, callouts, icons, and visual highlights\n- Executive summary pages and dense-content pages\n\nUse the target document’s existing data only. Where a reference visual cannot be supported by available data, use an equivalent structured layout rather than inventing content.\n\nDeliver a polished, consistent [OUTPUT FORMAT].\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "des",
      "apply",
      "reference",
      "design",
      "system",
      "document",
      "established",
      "visual",
      "new",
      "while"
    ],
    "status": "Approved Core",
    "readiness": "91% | Ready with source files",
    "requiredInputs": "REFERENCE DOCUMENT / STYLE GUIDE; TARGET DOCUMENT; OUTPUT FORMAT",
    "outputFormat": "Restyled document with unchanged content",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 12,
    "sourceId": "PL-EXL-01",
    "title": "Excel General Refinement",
    "category": "Excel Reporting",
    "description": "Transform an existing Excel report into an executive-ready dashboard while preserving data.",
    "prompt": "Transform the attached Excel report into an executive-level dashboard and reporting tool.\n\nPreserve all existing data, formulas, values, labels, and meaning. Do not delete, overwrite, or invent information.\n\nImprove:\n- Sheet structure, navigation, and visual hierarchy\n- KPI presentation, status indicators, and summary areas\n- Charts and dashboard elements based only on existing data\n- Column and row layout, formatting, readability, and consistency\n- Conditional formatting, filters, and priority signals where helpful\n- Executive storytelling, making key actions and trends easy to see\n\nUse a clean consulting-style layout aligned with [BRAND / COLOUR REQUIREMENTS]. Keep detailed source data accessible and separate it clearly from executive views.\n\nReturn the refined workbook with a brief note of major enhancements made.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "exl",
      "excel",
      "general",
      "refinement",
      "reporting",
      "transform",
      "existing",
      "report",
      "executive",
      "dashboard"
    ],
    "status": "Approved Core",
    "readiness": "94% | Ready with source files",
    "requiredInputs": "BRAND / COLOUR REQUIREMENTS",
    "outputFormat": "Refined Excel workbook with executive dashboard treatment",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 13,
    "sourceId": "PL-EXL-02",
    "title": "Excel Column and Text Refinement",
    "category": "Excel Reporting",
    "description": "Improve readability and layout of a working spreadsheet without altering content.",
    "prompt": "Refine the layout and readability of the attached Excel workbook without changing any data, formulas, labels, logic, or sheet structure.\n\nOptimise:\n- Column widths and row heights\n- Text wrapping, alignment, vertical positioning, and indentation\n- Header hierarchy, spacing, and visual grouping\n- Proportions for long text and numerical fields\n- Freeze panes, filters, and sensible viewing areas\n- Readability for both screen use and printing\n\nKeep the design professional, compact, and practical. Avoid excessive colours, oversized rows, decorative elements, or changes to the workbook’s meaning.\n\nReturn the updated workbook only.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "exl",
      "excel",
      "column",
      "text",
      "refinement",
      "reporting",
      "improve",
      "readability",
      "layout",
      "working"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "",
    "outputFormat": "Refined workbook, content unchanged",
    "complexity": "Intermediate",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 14,
    "sourceId": "PL-CAR-01",
    "title": "Executive Leadership Portfolio",
    "category": "Career Development",
    "description": "Create a board-ready portfolio that positions a leader for a senior role.",
    "prompt": "Create a high-impact executive leadership portfolio for [NAME], targeting [TARGET ROLE / LEVEL].\n\nProfessional context: [ROLE, ORGANISATION, REGION].\nCore achievements and evidence: [PASTE].\nLeadership scope: [TEAM, BUDGET, GEOGRAPHY, STAKEHOLDERS, PROGRAMMES].\nBrand requirements: [BRAND / COLOURS].\nOutput format: [WORD / PDF / POWERPOINT].\n\nStructure the portfolio around:\n- Executive profile and positioning statement\n- Strategic impact dashboard\n- Leadership pillars and operating model\n- Major transformation initiatives\n- KPI scorecards and measurable outcomes\n- Stakeholder ecosystem\n- Career timeline and awards\n- Case for target role\n\nUse precise, credible language. Do not invent metrics. Where evidence is missing, use a clearly marked placeholder or omit the claim.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "car",
      "executive",
      "leadership",
      "portfolio",
      "career",
      "development",
      "create",
      "board",
      "that",
      "positions"
    ],
    "status": "Approved Core",
    "readiness": "91% | Ready with evidence",
    "requiredInputs": "NAME; TARGET ROLE / LEVEL; ROLE, ORGANISATION, REGION; PASTE; TEAM, BUDGET, GEOGRAPHY, STAKEHOLDERS, PROGRAMMES; BRAND / COLOURS; WORD / PDF / POWERPOINT",
    "outputFormat": "Executive portfolio with dashboards and evidence-led narrative",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 15,
    "sourceId": "PL-CAR-02",
    "title": "Promotion Readiness and Role Fit Review",
    "category": "Career Development",
    "description": "Assess whether experience and evidence support a target role, with a direct development plan.",
    "prompt": "Assess whether the attached [CV / PERFORMANCE RECORD / PORTFOLIO] supports progression to [TARGET ROLE].\n\nUse this role framework or job description: [PASTE].\nEvaluate:\n- Scope, complexity, strategic impact, leadership, commercial influence, and technical expertise\n- Evidence against each key requirement\n- Strongest promotion arguments\n- Gaps or weak evidence that could challenge the case\n- Specific actions, achievements, or materials needed to close gaps\n\nReturn:\n1. Overall readiness rating: Ready now / Near ready / Development required.\n2. Requirement-by-requirement assessment table.\n3. Promotion case points.\n4. The three highest-value actions to strengthen the case.\n\nBe direct. Do not overstate weak evidence or assume responsibilities that are not documented.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "car",
      "promotion",
      "readiness",
      "role",
      "fit",
      "review",
      "career",
      "development",
      "assess",
      "whether"
    ],
    "status": "Approved Core",
    "readiness": "94% | Ready with evidence",
    "requiredInputs": "CV / PERFORMANCE RECORD / PORTFOLIO; TARGET ROLE; PASTE",
    "outputFormat": "Readiness assessment, gap table, and action plan",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 16,
    "sourceId": "PL-SPT-01",
    "title": "SharePoint Page Build Prompt",
    "category": "SharePoint",
    "description": "Generate a detailed SharePoint page build instruction that produces an operational workspace.",
    "prompt": "Create a SharePoint page for [PAGE NAME] that supports [BUSINESS PURPOSE].\n\nAudience: [USERS].\nPrimary actions: [ACTIONS].\nContent sources: [TRACKERS, LISTS, DOCUMENT LIBRARIES, LINKS].\nBrand constraints: [COLOURS / STYLE / LOGO RULES].\nAccessibility and governance requirements: [REQUIREMENTS].\n\nBuild a clear page structure with:\n- Hero / purpose area\n- Quick action section\n- Key tracker or status view\n- Process guidance and owner responsibilities\n- Document and template links\n- FAQ and support contact\n- Relevant alerts or deadlines\n\nRecommend the exact SharePoint web parts, section layouts, headings, button labels, and content order. Keep it buildable with standard SharePoint capabilities and avoid unsupported custom development unless requested.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "spt",
      "sharepoint",
      "page",
      "build",
      "generate",
      "detailed",
      "instruction",
      "that",
      "produces",
      "operational"
    ],
    "status": "Approved Core",
    "readiness": "93% | Ready with platform details",
    "requiredInputs": "PAGE NAME; BUSINESS PURPOSE; USERS; ACTIONS; TRACKERS, LISTS, DOCUMENT LIBRARIES, LINKS; COLOURS / STYLE / LOGO RULES; REQUIREMENTS",
    "outputFormat": "SharePoint page specification with exact web parts and content",
    "complexity": "Intermediate",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 17,
    "sourceId": "PL-COP-01",
    "title": "Microsoft 365 Copilot Agent Requirements",
    "category": "Copilot / Knowledge Management",
    "description": "Define an internal operational Copilot agent with grounded scope, responses, and safeguards.",
    "prompt": "Design the operating instructions for a Microsoft 365 Copilot agent named [AGENT NAME].\n\nBusiness purpose: [PURPOSE].\nUsers: [USER GROUP].\nApproved knowledge sources: [SHAREPOINT SITES / LIBRARIES / FILES].\nOut of scope: [OUT-OF-SCOPE TOPICS].\nRequired answer style: [STYLE].\nEscalation contacts: [CONTACTS / TEAM].\nSensitive-data rules: [RULES].\n\nWrite instructions that make the agent:\n- Answer only from approved sources where factual accuracy is needed\n- Distinguish confirmed information from missing information\n- Cite or link to source material where available\n- Ask for the minimum necessary clarification\n- Avoid legal, financial, HR, or compliance conclusions beyond its approved scope\n- Route users to the correct owner when evidence is unavailable\n\nReturn a copy-ready instruction set, suggested conversation starters, and a short test plan.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "cop",
      "microsoft",
      "365",
      "copilot",
      "agent",
      "requirements",
      "knowledge",
      "management",
      "define",
      "internal"
    ],
    "status": "Approved Core",
    "readiness": "93% | Ready with platform details",
    "requiredInputs": "AGENT NAME; PURPOSE; USER GROUP; SHAREPOINT SITES / LIBRARIES / FILES; OUT-OF-SCOPE TOPICS; STYLE; CONTACTS / TEAM; RULES",
    "outputFormat": "Agent instructions, starters, and test cases",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 18,
    "sourceId": "PL-PRC-01",
    "title": "Process Playbook Consolidation",
    "category": "Process Documentation",
    "description": "Create a single validated playbook from fragmented SOPs, trackers, and guidelines.",
    "prompt": "Create a consolidated [PROCESS NAME] Playbook for [BUSINESS UNIT / COUNTRY] using the supplied source material.\n\nSource documents: [LIST / ATTACHMENTS].\nAudience: [USERS].\nApproved terminology: [TERMS].\nValidation owner: [OWNER].\n\nConsolidate duplicated and conflicting content, but do not silently resolve factual conflicts. Highlight any item requiring owner validation in [HIGHLIGHT METHOD].\n\nInclude:\n- Purpose and scope\n- Roles and responsibilities\n- End-to-end process map\n- Step-by-step procedures\n- Required documents, systems, approvals, and controls\n- Service levels, exceptions, escalation path, and FAQs\n- Version-control and review process\n\nUse clear operational language. Preserve source-supported facts and flag gaps rather than guessing.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "prc",
      "process",
      "playbook",
      "consolidation",
      "documentation",
      "create",
      "single",
      "validated",
      "fragmented",
      "sops"
    ],
    "status": "Approved Core",
    "readiness": "92% | Ready with source files",
    "requiredInputs": "PROCESS NAME; BUSINESS UNIT / COUNTRY; LIST / ATTACHMENTS; USERS; TERMS; OWNER; HIGHLIGHT METHOD",
    "outputFormat": "Structured playbook with clearly flagged validation items",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 19,
    "sourceId": "PL-PRC-02",
    "title": "Operational Process Map and RACI",
    "category": "Process Design",
    "description": "Convert an existing process into a clear workflow, responsibilities matrix, and improvement actions.",
    "prompt": "Map and improve the following process: [PASTE PROCESS].\n\nContext: [BUSINESS UNIT / COUNTRY].\nStart trigger: [TRIGGER].\nEnd point: [OUTCOME].\nSystems involved: [SYSTEMS].\nStakeholders: [STAKEHOLDERS].\nKnown pain points: [PAIN POINTS].\nTarget service level: [SLA].\n\nCreate:\n1. A numbered end-to-end process map.\n2. A RACI matrix.\n3. Inputs, outputs, controls, and hand-off points.\n4. Bottlenecks, duplication, and risk points.\n5. A prioritised improvement backlog divided into quick wins, medium-term fixes, and strategic changes.\n\nDo not recommend automation or system replacement without evidence that it addresses a stated issue.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "prc",
      "operational",
      "process",
      "map",
      "raci",
      "design",
      "convert",
      "existing",
      "clear",
      "workflow"
    ],
    "status": "Approved Core",
    "readiness": "95% | Ready after inputs",
    "requiredInputs": "PASTE PROCESS; BUSINESS UNIT / COUNTRY; TRIGGER; OUTCOME; SYSTEMS; STAKEHOLDERS; PAIN POINTS; SLA",
    "outputFormat": "Process map, RACI, risks, and prioritised improvement backlog",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 20,
    "sourceId": "PL-MTG-01",
    "title": "Executive Meeting Brief",
    "category": "Executive Communication",
    "description": "Prepare a decision-focused briefing for a meeting using source records and known context.",
    "prompt": "Prepare a concise executive meeting brief for [MEETING TITLE] on [DATE].\n\nMeeting objective: [OBJECTIVE].\nAttendees: [ATTENDEES].\nSource material: [DOCUMENTS / TRACKERS / EMAILS / NOTES].\nDecisions required: [DECISIONS].\nKnown risks or sensitivities: [RISKS].\n\nReturn:\n- One-paragraph context\n- Decisions needed\n- Evidence and key data points\n- Risks, dependencies, and open questions\n- Recommended position and talking points\n- Clear follow-up actions with owner and due date placeholders\n\nDo not include background that does not support a decision. Separate facts from recommendations.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "mtg",
      "executive",
      "meeting",
      "brief",
      "communication",
      "prepare",
      "decision",
      "focused",
      "briefing",
      "records"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready to use",
    "requiredInputs": "MEETING TITLE; DATE; OBJECTIVE; ATTENDEES; DOCUMENTS / TRACKERS / EMAILS / NOTES; DECISIONS; RISKS",
    "outputFormat": "One-page decision brief",
    "complexity": "Intermediate",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 21,
    "sourceId": "PL-TRK-01",
    "title": "Structured Tracker Design",
    "category": "Excel / SharePoint",
    "description": "Design a tracker that is easy to operate, report from, and migrate to SharePoint or Power Apps.",
    "prompt": "Design a structured tracker for [PROCESS / PROJECT].\n\nUsers: [USERS].\nCases or records tracked: [RECORD TYPE].\nKey decisions the tracker must support: [DECISIONS].\nRequired reporting: [KPIS / REPORTS].\nSystems it may later connect to: [SYSTEMS].\n\nProvide:\n1. Recommended fields with field name, definition, type, mandatory status, controlled values, owner, and reporting purpose.\n2. Status model and allowable transitions.\n3. Unique ID approach and duplicate-prevention rules.\n4. Views or filters for each user group.\n5. Data-quality rules and exception flags.\n6. A migration-ready structure suitable for Excel first, then SharePoint or Power Apps.\n\nKeep it practical. Avoid fields that do not serve an operational or reporting purpose.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "trk",
      "structured",
      "tracker",
      "design",
      "excel",
      "sharepoint",
      "that",
      "easy",
      "operate",
      "report"
    ],
    "status": "Approved Core",
    "readiness": "95% | Ready after inputs",
    "requiredInputs": "PROCESS / PROJECT; USERS; RECORD TYPE; DECISIONS; KPIS / REPORTS; SYSTEMS",
    "outputFormat": "Data dictionary, status model, views, and quality controls",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 22,
    "sourceId": "PL-EXE-01",
    "title": "Source-Grounded Executive Summary",
    "category": "Executive Communication",
    "description": "Turn a set of reports, trackers, or records into a brief, evidence-based executive summary.",
    "prompt": "Create an executive summary from the supplied source material.\n\nAudience: [AUDIENCE].\nDecision or purpose: [PURPOSE].\nTime period: [DATE RANGE].\nSource material: [DOCUMENTS / TRACKERS / NOTES].\nMaximum length: [WORD COUNT / PAGES].\n\nInclude:\n- Bottom-line assessment\n- Most important metrics or evidence\n- Key changes, risks, dependencies, and decisions\n- Recommended next actions with owners where known\n- Data gaps or confidence limitations\n\nUse plain professional language. Prioritise what needs attention. Do not add facts or assumptions that are not supported by the sources.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "exe",
      "grounded",
      "executive",
      "summary",
      "communication",
      "turn",
      "set",
      "reports",
      "trackers",
      "records"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "AUDIENCE; PURPOSE; DATE RANGE; DOCUMENTS / TRACKERS / NOTES; WORD COUNT / PAGES",
    "outputFormat": "One-page executive summary with actions",
    "complexity": "Intermediate",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 23,
    "sourceId": "PL-REC-01",
    "title": "Employee Data Reconciliation and Correction Review",
    "category": "Data Reconciliation",
    "description": "Compare GRO, Workday, MOHRE, DWC, Oracle, or other employee records and produce an audit-ready correction plan.",
    "prompt": "Reconcile the supplied employee datasets for [ENTITY / POPULATION] as of [REPORTING DATE].\n\nPrimary objective: identify what the GRO Database is missing and what critical records or fields are missing or incorrect in Workday, while also identifying duplicates and material cross-system discrepancies.\n\nSources: [LIST FILES / SYSTEM EXPORTS].\nApproved source authority by field: [SOURCE-OF-TRUTH MATRIX].\nApproved exclusions or non-issues: [EXCLUSIONS].\nConfirmed issue rules: [ISSUE RULES].\n\nMatching order:\n1. Exact employee or person ID.\n2. Exact passport, Emirates ID, UID, visa, labour-card, or work-permit identifier where applicable.\n3. Exact work email or Oracle ID.\n4. Normalised name plus at least one supporting attribute.\n\nNever force an uncertain match. Label it Needs Review and state why.\n\nReturn:\n1. Executive summary with reconciled totals after exclusions.\n2. Records missing from the GRO Database and the fields available to complete them.\n3. Critical Workday records or fields that are missing, invalid, or inconsistent.\n4. Duplicate records and identifiers used by more than one employee.\n5. Material discrepancies by category, source value, recommended master value, confidence, owner, and action.\n6. A correction register for GRO team review.\n7. An audit table showing source totals, exclusions, matched records, unmatched records, and final issue counts.\n\nPreserve all original source values. Do not update, overwrite, or silently correct any source. Apply exclusions before calculating issue totals and clearly separate confirmed issues from review items.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "rec",
      "employee",
      "data",
      "reconciliation",
      "correction",
      "review",
      "compare",
      "gro",
      "workday",
      "mohre"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "ENTITY / POPULATION; REPORTING DATE; LIST FILES / SYSTEM EXPORTS; SOURCE-OF-TRUTH MATRIX; EXCLUSIONS; ISSUE RULES",
    "outputFormat": "Audit-ready reconciliation workbook or tables with correction register",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 24,
    "sourceId": "PL-M365-01",
    "title": "Microsoft 365 Build and Troubleshooting",
    "category": "Microsoft 365 Solutions",
    "description": "Diagnose and safely resolve SharePoint, Teams, Outlook, Power Apps, Power Automate, or Excel build issues.",
    "prompt": "Review and troubleshoot the Microsoft 365 issue below.\n\nPlatform and component: [APP / FEATURE / ACTION].\nGoal: [INTENDED BUSINESS OUTCOME].\nExpected result: [EXPECTED RESULT].\nActual result: [ACTUAL RESULT / ERROR].\nEvidence: [SCREENSHOTS / EXPORT / FORMULA / CONFIGURATION / SAMPLE DATA].\nConstraints: [PERMISSIONS / ENVIRONMENT / CONNECTORS / DATA SENSITIVITY / NO-CHANGE AREAS].\n\nFirst identify the most likely root cause, missing dependencies, affected connections or permissions, and any risk of changing the current setup.\n\nThen provide only the next safe steps in exact click-by-click order. Use the smallest change that can test or resolve the issue. Do not redesign the solution unless the current design cannot meet the stated outcome.\n\nValidate relevant fields, formulas, filters, connections, permissions, dynamic content, and platform limitations. If evidence is insufficient, ask only the minimum questions needed before recommending a change.\n\nEnd with:\n- Test checklist\n- Expected test results\n- Rollback point, if applicable\n- Definition of done\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "m365",
      "microsoft",
      "365",
      "build",
      "troubleshooting",
      "solutions",
      "diagnose",
      "safely",
      "resolve",
      "sharepoint"
    ],
    "status": "Approved Core",
    "readiness": "98% | Ready to use",
    "requiredInputs": "APP / FEATURE / ACTION; INTENDED BUSINESS OUTCOME; EXPECTED RESULT; ACTUAL RESULT / ERROR; SCREENSHOTS / EXPORT / FORMULA / CONFIGURATION / SAMPLE DATA; PERMISSIONS / ENVIRONMENT / CONNECTORS / DATA SENSITIVITY / NO-CHANGE AREAS",
    "outputFormat": "Root cause, next safe steps, test checklist, and definition of done",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 25,
    "sourceId": "PL-GRK-01",
    "title": "GRO Knowledge Base Complete Raw Content Extraction",
    "category": "GRO Knowledge Management",
    "description": "Extract all reusable GRO source content into one controlled raw-content document before restructuring.",
    "prompt": "Extract reusable raw content from [SOURCE FOLDER / ATTACHED FILES] into one document titled “[OUTPUT TITLE]”.\n\nThis is raw-content extraction only. Do not create knowledge articles, employee guides, summaries, or final publication structure.\n\nGroup content by original source file and record:\n- File name and folder path\n- File type\n- Location, authority, or service identified\n- Full reusable raw content from body text, tables, text boxes, headers, footers, and embedded objects when readable\n- Duplicate or supporting-document status\n- Unreadable, image-only, missing, or incomplete content\n\nSource rules:\n- Prefer Word over PDF when the content is equivalent.\n- Do not repeat duplicate-format copies.\n- Keep communication content separate from process content.\n- Preserve original facts, wording, figures, contacts, and requirements.\n- Do not invent, reconcile, update, or interpret missing information.\n- Mark uncertain items “Requires review” and inaccessible visual content “Manual source review required.”\n\nReturn one complete extraction document with a source inventory and a short extraction-quality summary.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "grk",
      "gro",
      "knowledge",
      "base",
      "complete",
      "raw",
      "content",
      "extraction",
      "management",
      "extract"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "SOURCE FOLDER / ATTACHED FILES; OUTPUT TITLE",
    "outputFormat": "One complete source-grouped raw-content extraction document",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 26,
    "sourceId": "PL-GRK-02",
    "title": "GRO Raw Content Conversion Plan",
    "category": "GRO Knowledge Management",
    "description": "Plan how extracted GRO content will become structured datasets and later formatted employee guides without processing it yet.",
    "prompt": "Create a practical conversion plan for [RAW CONTENT SOURCE] without converting or rewriting the content.\n\nProject objective:\nPhase 1: review, separate, clean, classify, and organise extracted raw content into structured employee-guide-ready datasets.\nPhase 2: convert approved structured datasets into formatted Microsoft Word employee guides using [APPROVED REFERENCE STYLE].\n\nThe plan must define:\n1. Intake and source inventory.\n2. Skip decisions for email threads, images, screenshots, duplicate copies, unreadable content, and material that is not suitable for an employee guide.\n3. Content classification and document-boundary decisions.\n4. Source precedence and conflict handling.\n5. Data cleaning and standardisation rules that preserve meaning.\n6. The Phase 1 dataset structure and quality gate.\n7. The Phase 2 generation, formatting, validation, and approval sequence.\n8. Exceptions, unresolved gaps, ownership, dependencies, stopping rules, and definition of done for each phase.\n\nDo not process the raw data, create datasets, generate Word files, or add government requirements, fees, timelines, approvals, procedures, contacts, or links.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "grk",
      "gro",
      "raw",
      "content",
      "conversion",
      "plan",
      "knowledge",
      "management",
      "how",
      "extracted"
    ],
    "status": "Approved Core",
    "readiness": "98% | Ready after inputs",
    "requiredInputs": "RAW CONTENT SOURCE; APPROVED REFERENCE STYLE",
    "outputFormat": "Two-phase conversion plan with skip rules, gates, and definition of done",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 27,
    "sourceId": "PL-GRK-03",
    "title": "GRO Raw Content to Employee Guide Dataset",
    "category": "GRO Knowledge Management",
    "description": "Execute Phase 1 by converting approved raw GRO content into a clean structured dataset without generating a Word guide.",
    "prompt": "Convert the supplied approved raw GRO content into a structured employee-guide-ready dataset for [SERVICE / TOPIC / LOCATION].\n\nThis is Phase 1 data structuring only. Do not generate, format, or simulate a final Microsoft Word employee guide.\n\nSkip content that is primarily an email thread, image, screenshot, duplicate copy, unreadable source, or not suitable for employee-guide use. Record every skipped item with the reason.\n\nUse only source-supported content. Do not add or infer government requirements, fees, timelines, approvals, procedures, contacts, links, or eligibility rules.\n\nStructure the dataset as:\n- Proposed document name\n- Content classification\n- Source files used and source precedence\n- Document Overview: Applies to | Purpose | Contains | Other\n- Required documents table\n- Process steps table\n- Medical test requirements, if source-supported and applicable\n- Roles and responsibilities\n- Timeline and dependencies\n- Escalation contacts, if source-supported\n- Gaps, conflicts, and items requiring validation\n\nRemove drafting notes, duplicate wording, and empty placeholders. Preserve factual qualifiers and location-specific differences. Return the structured dataset and a short quality-check table only.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "grk",
      "gro",
      "raw",
      "content",
      "employee",
      "guide",
      "dataset",
      "knowledge",
      "management",
      "execute"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "SERVICE / TOPIC / LOCATION",
    "outputFormat": "Structured employee-guide dataset with source and quality controls",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 28,
    "sourceId": "PL-GRK-04",
    "title": "GRO Employee Guide Generation from Approved Dataset",
    "category": "GRO Knowledge Management",
    "description": "Execute Phase 2 by converting an approved structured dataset into a publication-ready Word employee guide.",
    "prompt": "Convert the approved structured dataset for [SERVICE / TOPIC / LOCATION] into a publication-ready Microsoft Word employee guide using [APPROVED REFERENCE DOCUMENT / STYLE].\n\nUse the dataset as the factual source of truth. Preserve the approved wording, facts, qualifiers, sequence, and location differences. Do not introduce new government requirements, fees, timelines, approvals, procedures, contacts, links, or unsupported content.\n\nRequired structure:\n1. Title and subtitle\n2. Document metadata table\n3. Document Overview: Applies to | Purpose | Contains | Other\n4. Required documents\n5. Process steps\n6. Medical test requirements, if applicable\n7. Roles and responsibilities\n8. Timeline and dependencies\n9. Escalation contacts\n10. Final confirmation or closure guidance\n\nDo not add “At a glance,” “Key requirements,” or any manifest section. Omit unsupported optional sections rather than publishing placeholders or drafting notes.\n\nMatch the approved layout, typography, table rules, header, footer, page balance, and brand colours. Validate section order, content completeness, table consistency, page breaks, orphaned bullets, and unsupported claims before delivery.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "grk",
      "gro",
      "employee",
      "guide",
      "generation",
      "approved",
      "dataset",
      "knowledge",
      "management",
      "execute"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready with source files",
    "requiredInputs": "SERVICE / TOPIC / LOCATION; APPROVED REFERENCE DOCUMENT / STYLE",
    "outputFormat": "Publication-ready Word employee guide matching the approved reference",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 29,
    "sourceId": "PL-GOV-01",
    "title": "Government Requirements Source Verification",
    "category": "Government Relations Compliance",
    "description": "Audit GRO procedures or guidance against current official government sources before publication or operational use.",
    "prompt": "Verify the supplied [PROCEDURE / GUIDE / REQUIREMENTS TABLE] for [SERVICE, AUTHORITY, LOCATION] against current official government sources.\n\nVerification date: [DATE].\nApproved source priority: [OFFICIAL AUTHORITY ORDER].\n\nCheck every factual requirement, document, eligibility condition, fee, timeline, approval, process step, portal, contact, exception, and location-specific rule.\n\nFor each item, classify it as:\n- Verified and current\n- Partially verified\n- Outdated or conflicting\n- Not found in official sources\n- Requires owner confirmation\n\nReturn a line-by-line audit table with: section/item | existing statement | status | verified current requirement | official source | source date or last update | recommended action.\n\nUse only official government, regulator, municipality, ministry, pension, free-zone, or authority sources unless explicitly authorised otherwise. Do not silently rewrite the document or treat absence from a website as proof that a requirement is invalid. Separate sourced findings from analyst inference.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "gov",
      "government",
      "requirements",
      "verification",
      "relations",
      "compliance",
      "audit",
      "gro",
      "procedures",
      "guidance"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "PROCEDURE / GUIDE / REQUIREMENTS TABLE; SERVICE, AUTHORITY, LOCATION; DATE; OFFICIAL AUTHORITY ORDER",
    "outputFormat": "Line-by-line government source audit with official links and actions",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 30,
    "sourceId": "PL-SKG-01",
    "title": "AI Skill Register Consolidation and Governance Review",
    "category": "AI Portfolio Governance",
    "description": "Maintain one evidence-based register of active, draft, replaced, and retired AI skills without building or editing the skills.",
    "prompt": "Review only the attached skill documents and update one consolidated Skill Register.\n\nFor every skill, record:\n- Skill name\n- Status: Active, Draft, Under Review, Retired, or Replaced\n- Purpose\n- Main responsibilities\n- Clear boundaries and exclusions\n- Expected inputs and outputs\n- Owner or functional area\n- Current version\n- Dependencies\n- Known overlaps\n- Recommended overlap resolution\n- Replacement or retirement notes\n- Last reviewed date\n\nGovernance rules:\n1. Each skill must have one clear primary responsibility.\n2. Workflow Router only selects the correct existing skill or capability.\n3. Skill Portfolio Manager is the sole portfolio-governance owner.\n4. Prompt & Workflow Optimizer only improves instruction quality.\n5. AI QA & Source Audit performs evidence-based verification and does not conduct fresh regulatory research unless requested.\n6. Prefer extending or merging an existing skill over creating a duplicate.\n7. Do not create, edit, install, retire, or delete skills from this task.\n8. Do not silently resolve unclear ownership or scope conflicts.\n9. Mark missing details “Not defined” or “Requires review.”\n\nReturn the updated register, overlap findings, recommended merge/extend/retire actions, missing information, and a concise changelog.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "skg",
      "skill",
      "register",
      "consolidation",
      "governance",
      "review",
      "portfolio",
      "maintain",
      "one",
      "evidence"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready with source files",
    "requiredInputs": "",
    "outputFormat": "Consolidated Skill Register with governance findings and changelog",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 31,
    "sourceId": "PL-AIR-01",
    "title": "Weekly AI Portfolio Review",
    "category": "AI Portfolio Governance",
    "description": "Assess progress, health, reuse opportunities, and priorities across recent ChatGPT and Codex work.",
    "prompt": "Review my ChatGPT and Codex activity from the past [NUMBER] days and produce an AI portfolio review using only observable conversation evidence.\n\nDo not infer undocumented progress, ownership, completion, or value.\n\nMaximum length: [WORD LIMIT].\nOutput format: [EDITABLE CANVAS / DOCUMENT / CHAT].\n\nUse these sections and omit any section with no evidence:\n1. Executive summary\n2. Completed work\n3. Portfolio health\n4. Reuse and standardisation opportunities\n5. Top three priorities for the next period\n6. Decisions requiring attention\n\nIdentify duplicate assets, overlapping skills, unfinished threads, stalled decisions, and work that should become a reusable prompt, checklist, skill, or scheduled task. Keep the review concise, objective, constructive, and specific.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "air",
      "weekly",
      "portfolio",
      "review",
      "governance",
      "assess",
      "progress",
      "health",
      "reuse",
      "opportunities"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready after inputs",
    "requiredInputs": "NUMBER; WORD LIMIT; EDITABLE CANVAS / DOCUMENT / CHAT",
    "outputFormat": "Concise evidence-based AI portfolio review",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 32,
    "sourceId": "PL-CHR-01",
    "title": "ChatGPT Conversation Pattern Review",
    "category": "Personal Productivity",
    "description": "Identify recurring work patterns, blockers, unfinished threads, and reusable assets from recent chats.",
    "prompt": "Review my ChatGPT conversations from the past [NUMBER] days and identify recurring observable patterns in my thinking, work style, priorities, decision-making, communication, and problem-solving.\n\nHighlight productive habits, repeated blockers, unfinished threads, common requests, areas of overcomplication, and underused ChatGPT capabilities. Use only evidence visible in the conversations and avoid unsupported psychological assumptions.\n\nOutput requirements:\n- Start with a concise 5–6 line executive summary.\n- Then provide exactly 10 action-oriented findings in a clean table.\n- For each finding include evidence, impact, and one practical recommendation.\n- End every finding with a clear next step.\n- Identify the three most repeated request types and recommend whether each should become a saved prompt, scheduled task, checklist, or skill.\n\nTone: objective, constructive, and specific.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "chr",
      "chatgpt",
      "conversation",
      "pattern",
      "review",
      "personal",
      "productivity",
      "identify",
      "recurring",
      "work"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready after inputs",
    "requiredInputs": "NUMBER",
    "outputFormat": "Executive summary plus exactly 10 evidence-based action findings",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 33,
    "sourceId": "PL-CPT-01",
    "title": "Microsoft Copilot Prompt Pack Builder",
    "category": "Microsoft 365 Copilot",
    "description": "Convert a repeated Microsoft 365 analysis task into a controlled, team-ready Copilot Prompt Pack.",
    "prompt": "Create a Microsoft Copilot Prompt Pack for [TASK / ANALYSIS NAME].\n\nUsers: [USER GROUP AND LICENCE LEVEL].\nBusiness purpose: [PURPOSE].\nApproved sources: [OUTLOOK / SHARED MAILBOX / SHAREPOINT / TEAMS / ONEDRIVE / FILES].\nWork content or identifiers: [VERIFIED IDS / FOLDERS / MAILBOXES].\nEvidence priority: [SOURCE ORDER].\nRequired output: [TABLE / SUMMARY / ACTION LIST].\n\nProvide:\n1. Clear Prompt Pack name.\n2. Full copy-ready prompt instructions.\n3. Knowledge and source settings.\n4. Work Content entries using only verified identifiers.\n5. Exact output table columns and sorting rules.\n6. Source-grounding, duplicate-handling, missing-data, and uncertainty rules.\n7. A short user guide and three realistic test cases.\n\nKeep the wording simple enough for first-time Copilot users. Distinguish capabilities available in basic Copilot Chat from Microsoft 365 Copilot. Do not invent connectors, content IDs, permissions, or evidence.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "cpt",
      "microsoft",
      "copilot",
      "pack",
      "builder",
      "365",
      "convert",
      "repeated",
      "analysis",
      "task"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready with platform details",
    "requiredInputs": "TASK / ANALYSIS NAME; USER GROUP AND LICENCE LEVEL; PURPOSE; OUTLOOK / SHARED MAILBOX / SHAREPOINT / TEAMS / ONEDRIVE / FILES; VERIFIED IDS / FOLDERS / MAILBOXES; SOURCE ORDER; TABLE / SUMMARY / ACTION LIST",
    "outputFormat": "Team-ready Copilot Prompt Pack with prompt, sources, output, and tests",
    "complexity": "Advanced",
    "frequency": "High",
    "value": "5"
  },
  {
    "id": 34,
    "sourceId": "PL-CNB-01",
    "title": "Copilot Notebook Knowledge Guide Builder",
    "category": "Microsoft 365 Copilot",
    "description": "Turn a work topic into a beginner-friendly Notebook guide with low-engineered, powerful prompts for a team.",
    "prompt": "Design a Copilot Notebook knowledge guide for [TOPIC] for [TEAM / ROLE].\n\nUser level: [FIRST-TIME / BASIC / INTERMEDIATE].\nLicence context: [BASIC CHAT / MICROSOFT 365 COPILOT].\nApproved work sources: [SOURCES].\nBusiness scenarios: [SCENARIOS].\n\nBefore creating the guide, ask no more than five focused questions if essential instructions are unclear.\n\nThe guide must:\n- Explain the topic in simple, low-corporate language.\n- Separate basic Copilot Chat capabilities from Microsoft 365 Copilot capabilities.\n- Use short, practical, visually clean tables and bullet points.\n- Include source-reliability and data-quality guidance.\n- Provide reusable prompts for real work scenarios.\n- Keep prompt wording easy for first-time users while preserving useful controls.\n- State what information the user must provide and what Copilot cannot reliably do.\n\nReturn a proposed guide structure and sample prompts first. Generate the full knowledge guide only after approval.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "cnb",
      "copilot",
      "notebook",
      "knowledge",
      "guide",
      "builder",
      "microsoft",
      "365",
      "turn",
      "work"
    ],
    "status": "Approved Core",
    "readiness": "95% | Ready with platform details",
    "requiredInputs": "TOPIC; TEAM / ROLE; FIRST-TIME / BASIC / INTERMEDIATE; BASIC CHAT / MICROSOFT 365 COPILOT; SOURCES; SCENARIOS",
    "outputFormat": "Approval-ready Notebook outline and beginner-friendly sample prompts",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 35,
    "sourceId": "PL-SIT-01",
    "title": "ChatGPT Work Site Build from A to Z",
    "category": "ChatGPT Work / Sites",
    "description": "Design, build, test, host, and publish a complete site inside ChatGPT Work using a production-ready brief.",
    "prompt": "Build a production-ready [SITE TYPE] named “[SITE NAME]” inside ChatGPT Work from initial definition through hosting and publication.\n\nUsers and roles: [USERS / ROLES].\nCore use cases: [USE CASES].\nRequired pages and functions: [FEATURES].\nData and file requirements: [DATA / STORAGE / UPLOAD LIMITS].\nAccess model: [PRIVATE / TEAM / PUBLIC].\nDesign direction: minimal, modern, and familiar, without copying protected product design.\n\nOwn the full lifecycle:\n1. Confirm scope, assumptions, and definition of done.\n2. Design information architecture, user flows, screens, data model, permissions, and error states.\n3. Select a supported stack and explain major choices simply.\n4. Build the application and connect supported storage and database services.\n5. Add validation, responsive design, accessibility, security, privacy, backup, and recovery controls.\n6. Test core journeys, permissions, uploads, empty states, errors, and mobile use.\n7. Deploy, host, publish, and verify the production URL.\n8. Provide a simple operating guide, known limitations, and future backlog.\n\nUse language clear enough for a 10-year-old to understand in explanations and progress updates. Do not claim deployment or verification unless it was actually completed.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "sit",
      "chatgpt",
      "work",
      "site",
      "build",
      "sites",
      "design",
      "test",
      "host",
      "publish"
    ],
    "status": "Approved Core",
    "readiness": "94% | Ready with platform details",
    "requiredInputs": "SITE TYPE; SITE NAME; USERS / ROLES; USE CASES; FEATURES; DATA / STORAGE / UPLOAD LIMITS; PRIVATE / TEAM / PUBLIC",
    "outputFormat": "Working hosted site, verified production URL, and simple operating guide",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 36,
    "sourceId": "PL-SIT-02",
    "title": "Existing ChatGPT Site Recovery and Deployment Verification",
    "category": "ChatGPT Work / Sites",
    "description": "Recover and verify an existing ChatGPT-hosted site without rebuilding it unnecessarily.",
    "prompt": "Recover and verify the existing ChatGPT site “[SITE NAME]” at [PRODUCTION URL].\n\nDo not rebuild the site unless recovery is demonstrably impossible.\n\nInspect:\n- Existing project and saved versions\n- Deployed version and production health\n- Build, runtime, and deployment logs\n- Database and file-storage connections\n- Environment settings, access controls, and account permissions\n- Recent changes that may explain the failure\n\nUse the smallest safe fix. Preserve existing data, structure, and working features. Save and deploy the corrected version only after validation.\n\nThen open the production URL and verify the landing page, sign-in flow, database access, file storage, core user journey, and intended access level.\n\nReturn: current status | root cause | actions taken | tests completed | unresolved risks | any manual step required | verified final URL.\n\nUse simple language. Do not report the site as fixed or verified unless the production checks succeeded.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "sit",
      "existing",
      "chatgpt",
      "site",
      "recovery",
      "deployment",
      "verification",
      "work",
      "sites",
      "recover"
    ],
    "status": "Approved Core",
    "readiness": "96% | Ready with platform details",
    "requiredInputs": "SITE NAME; PRODUCTION URL",
    "outputFormat": "Recovered deployment with production verification report",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 37,
    "sourceId": "PL-CAR-03",
    "title": "Senior Government Relations Career Radar",
    "category": "Career Development",
    "description": "Find newly posted senior UAE and GCC government-relations roles that match the user's experience and target level.",
    "prompt": "Search for newly posted or materially updated senior Government Relations, Government Affairs, Public Affairs, Regulatory Affairs, Immigration, Mobility, or Workforce Compliance roles in [UAE / GCC LOCATIONS].\n\nTarget level: [SENIOR MANAGER / HEAD / DIRECTOR].\nCandidate profile: [CV / EXPERIENCE SUMMARY].\nMinimum compensation or constraints: [REQUIREMENTS].\nLookback period: [DAYS].\n\nReturn up to eight relevant roles with: title | organisation | location | posting date | direct link | fit rationale | strongest matching evidence | key gaps or risks.\n\nRank and highlight the top three. Exclude junior, coordinator, administrator, PRO-only, expired, duplicated, or clearly unsuitable roles. Do not infer salary or responsibilities that are not stated.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "car",
      "senior",
      "government",
      "relations",
      "career",
      "radar",
      "development",
      "find",
      "newly",
      "posted"
    ],
    "status": "Approved Core",
    "readiness": "95% | Ready after inputs",
    "requiredInputs": "UAE / GCC LOCATIONS; SENIOR MANAGER / HEAD / DIRECTOR; CV / EXPERIENCE SUMMARY; REQUIREMENTS; DAYS",
    "outputFormat": "Ranked career opportunity table with top-three recommendations",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 38,
    "sourceId": "PL-CAR-04",
    "title": "Monthly Senior Manager Impact Check-In",
    "category": "Career Development",
    "description": "Capture monthly evidence and convert it into promotion-ready achievements and metrics.",
    "prompt": "Run a monthly Senior Manager impact check-in for [MONTH / PERIOD].\n\nAsk one question at a time and capture evidence across:\n1. Strategic initiatives and business impact\n2. Team leadership and operating-model improvement\n3. Regulatory, compliance, or risk outcomes\n4. Stakeholder influence and executive visibility\n5. Process, technology, AI, or automation improvement\n6. Cost, time, quality, service, or employee-experience results\n\nAsk for measurable evidence, source records, dates, stakeholders, and the user’s personal contribution. Do not invent metrics or overstate shared achievements.\n\nAfter the questions, return:\n- Concise monthly achievement record\n- Three promotion-ready achievement bullets\n- One executive impact paragraph\n- Three metrics to track next month\n- Evidence gaps that should be documented\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "car",
      "monthly",
      "senior",
      "manager",
      "impact",
      "check",
      "career",
      "development",
      "capture",
      "evidence"
    ],
    "status": "Approved Core",
    "readiness": "97% | Ready to use",
    "requiredInputs": "MONTH / PERIOD",
    "outputFormat": "Monthly evidence record, promotion bullets, executive paragraph, and metrics",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  },
  {
    "id": 39,
    "sourceId": "PL-M365-02",
    "title": "AI and Microsoft 365 Practical Workflow Brief",
    "category": "Microsoft 365 Solutions",
    "description": "Research practical, current AI and Microsoft 365 improvements that can be applied to Government Relations work.",
    "prompt": "Research three practical improvements using current ChatGPT, Microsoft 365, Outlook, Teams, SharePoint, Copilot, Power Apps, Power Automate, or Excel capabilities for [BUSINESS AREA / USE CASE].\n\nFor each improvement provide:\n- Tool or feature\n- What it does\n- Specific Government Relations or employee-lifecycle use case\n- Why it is better than the current approach\n- Practical first step\n- Required licence, access, or dependency\n- Main risk or limitation\n- Credible official source link\n\nPrioritise improvements that are realistic for the user’s current Microsoft environment and can be tested safely. Avoid speculative features, generic productivity tips, high-complexity IT programmes, or recommendations that duplicate existing solutions.\n\nREADINESS CHECK\nBefore starting, identify unresolved bracketed placeholders. Ask only for essential missing inputs. If the task can proceed safely, use reasonable low-risk assumptions and label them. Never invent source facts, permissions, platform capabilities, dates, or evidence.",
    "tags": [
      "m365",
      "microsoft",
      "365",
      "practical",
      "workflow",
      "brief",
      "solutions",
      "research",
      "current",
      "improvements"
    ],
    "status": "Approved Core",
    "readiness": "95% | Ready after inputs",
    "requiredInputs": "BUSINESS AREA / USE CASE",
    "outputFormat": "Three current, source-backed workflow improvements with first steps",
    "complexity": "Advanced",
    "frequency": "Medium",
    "value": "5"
  }
];

export const categories = [
  "All prompts",
  ...Array.from(new Set(prompts.map((prompt) => prompt.category))).sort((a, b) => a.localeCompare(b)),
];
